__MODULE__ = "FreeGPT 🤖"
__HELP__ = (
    "<code>.ai &lt;вопрос&gt;</code> — Получить потоковый текстовый ответ\n"
    "<code>.aimage &lt;описание&gt;</code> — Создать изображение"
)

import asyncio
import html
from urllib.parse import urlparse

import config
from pyrogram import Client, filters
from pyrogram.errors import FloodWait, MessageNotModified
from pyrogram.types import Message

from utils import ONLY_ME, PREFIXES


TEXT_MODELS = {
    "standard",
    "online",
    "gemma-4",
    "gemini-2.5-flash-lite",
    "deepseek-v3.2",
}


def normalize_text_model(value: str) -> str:
    return value if value in TEXT_MODELS else "standard"


AI_MODEL = normalize_text_model(getattr(config, "AI_MODEL", "standard"))
AI_IMAGE_MODEL = getattr(config, "AI_IMAGE_MODEL", "flux")
AI_ROLE = getattr(config, "AI_ROLE", "user")
AI_STREAM_DELAY = max(float(getattr(config, "AI_STREAM_DELAY", 1.2)), 0.5)
MAX_AI_RESPONSE_CHARS = 24000
PROVIDER_AD = "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai"


def strip_provider_ad(value: str) -> str:
    return value.replace(PROVIDER_AD, "").strip()


def split_text(value: str, limit: int = 3000) -> list[str]:
    if limit < 1:
        raise ValueError("limit must be positive")
    return [value[index:index + limit] for index in range(0, len(value), limit)] or [""]


def split_html_text(value: str, limit: int = 3000) -> list[str]:
    chunks = []
    current = []
    escaped_length = 0

    for character in value:
        character_length = len(html.escape(character))
        if current and escaped_length + character_length > limit:
            chunks.append("".join(current))
            current = []
            escaped_length = 0
        current.append(character)
        escaped_length += character_length

    if current or not chunks:
        chunks.append("".join(current))
    return chunks


def format_answer(question: str, answer: str, model: str) -> str:
    return (
        f"<b>Вопрос:</b> {html.escape(question)}\n\n"
        f"<b>Ответ:</b> {html.escape(answer)}\n\n"
        f"<b>Модель:</b> <code>{html.escape(model)}</code>"
    )


def append_bounded(current: str, chunk: str, limit: int) -> tuple[str, bool]:
    remaining = max(limit - len(current), 0)
    combined = current + chunk[:remaining]
    return combined, len(chunk) > remaining


def _create_stream(prompt: str):
    from g4f.client import Client as GPTClient
    from g4f.Provider.DeepAI import DeepAI

    return GPTClient(provider=DeepAI).chat.completions.create(
        model=AI_MODEL,
        messages=[{"role": AI_ROLE, "content": prompt}],
        stream=True,
    )


def _next_content(stream):
    try:
        chunk = next(stream)
    except StopIteration:
        return None, True

    content = getattr(chunk.choices[0].delta, "content", None)
    return content, False


def _generate_image(prompt: str):
    from g4f.client import Client as GPTClient
    from g4f.Provider.Pollinations import Pollinations
    from g4f.Provider.PollinationsImage import PollinationsImage

    Pollinations.get_models(timeout=15)
    return GPTClient(media_provider=PollinationsImage).images.generate(
        model=AI_IMAGE_MODEL,
        prompt=prompt,
        response_format="url",
        download_media=False,
    )


async def _safe_edit(msg: Message, text: str):
    try:
        await msg.edit(text)
    except FloodWait as exc:
        await asyncio.sleep(exc.value)
        await msg.edit(text)
    except MessageNotModified:
        pass


@Client.on_message(filters.command("ai", prefixes=PREFIXES) & ONLY_ME)
async def ai_handler(client: Client, msg: Message):
    parts = (msg.text or "").split(maxsplit=1)
    if len(parts) != 2 or not parts[1].strip():
        await msg.edit("Задайте вопрос: <code>.ai ваш вопрос</code>")
        return

    prompt = parts[1].strip()
    if len(prompt) > 8000:
        await msg.edit("Вопрос слишком длинный. Максимум: 8000 символов.")
        return

    await msg.edit("Получаю ответ...")
    answer = ""
    last_update = 0.0
    stream = None

    try:
        stream = await asyncio.to_thread(_create_stream, prompt)
        loop = asyncio.get_running_loop()
        while True:
            content, finished = await asyncio.to_thread(_next_content, stream)
            if finished:
                break
            if content:
                answer, reached_limit = append_bounded(
                    answer, content, MAX_AI_RESPONSE_CHARS
                )
                if reached_limit:
                    break
            now = loop.time()
            if answer and now - last_update >= AI_STREAM_DELAY:
                preview = split_html_text(strip_provider_ad(answer), 2600)[0]
                await _safe_edit(msg, format_answer(prompt[:150], preview + "...", AI_MODEL))
                last_update = now
    except Exception:
        await msg.edit("AI-провайдер сейчас недоступен. Повторите запрос позже.")
        return
    finally:
        close = getattr(stream, "close", None)
        if close:
            try:
                await asyncio.to_thread(close)
            except Exception:
                pass

    answer = strip_provider_ad(answer)
    if not answer:
        await msg.edit("AI-провайдер вернул пустой ответ.")
        return

    chunks = split_html_text(answer, 3000)
    await _safe_edit(msg, format_answer(prompt[:150], chunks[0], AI_MODEL))
    for chunk in chunks[1:]:
        await client.send_message(
            msg.chat.id,
            f"<b>Продолжение:</b>\n{html.escape(chunk)}",
            message_thread_id=msg.message_thread_id,
        )


@Client.on_message(filters.command("aimage", prefixes=PREFIXES) & ONLY_ME)
async def ai_image_handler(client: Client, msg: Message):
    parts = (msg.text or "").split(maxsplit=1)
    if len(parts) != 2 or not parts[1].strip():
        await msg.edit("Опишите изображение: <code>.aimage описание</code>")
        return

    prompt = parts[1].strip()
    if len(prompt) > 2000:
        await msg.edit("Описание слишком длинное. Максимум: 2000 символов.")
        return

    await msg.edit("Создаю изображение...")
    try:
        response = await asyncio.to_thread(_generate_image, prompt)
        image_url = response.data[0].url
        parsed = urlparse(image_url)
        if parsed.scheme != "https" or not parsed.netloc:
            raise ValueError("unsafe image URL")
        await client.send_document(
            msg.chat.id,
            image_url,
            caption=(
                f"<b>Описание:</b> <code>{html.escape(prompt[:600])}</code>\n"
                f"<b>Модель:</b> <code>{html.escape(AI_IMAGE_MODEL)}</code>"
            ),
            message_thread_id=msg.message_thread_id,
        )
    except Exception:
        await msg.edit("Не удалось создать изображение. Повторите позже.")
        return

    await msg.delete()
