import unittest
import sys
import types
from unittest.mock import AsyncMock, patch

from tests.stubs import install_pyrogram_stubs

install_pyrogram_stubs()


class FreeGPTTest(unittest.TestCase):
    def test_strip_provider_ad_removes_known_footer(self):
        from modules.freegpt import strip_provider_ad

        text = "Ответ\nGenerated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai"

        self.assertEqual(strip_provider_ad(text), "Ответ")

    def test_format_answer_escapes_prompt_and_answer(self):
        from modules.freegpt import format_answer

        text = format_answer("<question>", "<answer>", "gpt-4o")

        self.assertIn("&lt;question&gt;", text)
        self.assertIn("&lt;answer&gt;", text)
        self.assertNotIn("<question>", text)

    def test_split_text_preserves_content(self):
        from modules.freegpt import split_text

        text = "word " * 100
        chunks = split_text(text, 40)

        self.assertEqual("".join(chunks), text)
        self.assertTrue(all(len(chunk) <= 40 for chunk in chunks))

    def test_split_html_text_obeys_limit_after_escaping(self):
        import html
        from modules.freegpt import split_html_text

        text = "<&" * 40
        chunks = split_html_text(text, 25)

        self.assertEqual("".join(chunks), text)
        self.assertTrue(all(len(html.escape(chunk)) <= 25 for chunk in chunks))

    def test_create_stream_pins_browserless_provider(self):
        from modules.freegpt import _create_stream

        deepai = object()
        calls = {}

        class FakeCompletions:
            def create(self, **kwargs):
                calls["create"] = kwargs
                return iter(())

        class FakeClient:
            def __init__(self, **kwargs):
                calls["client"] = kwargs
                self.chat = types.SimpleNamespace(completions=FakeCompletions())

        client_module = types.ModuleType("g4f.client")
        client_module.Client = FakeClient
        provider_module = types.ModuleType("g4f.Provider.DeepAI")
        provider_module.DeepAI = deepai

        with patch.dict(sys.modules, {
            "g4f.client": client_module,
            "g4f.Provider.DeepAI": provider_module,
        }):
            _create_stream("hello")

        self.assertIs(calls["client"]["provider"], deepai)

    def test_normalize_text_model_falls_back_to_browserless_default(self):
        from modules.freegpt import normalize_text_model

        self.assertEqual(normalize_text_model("gpt-4o"), "standard")
        self.assertEqual(normalize_text_model("deepseek-v3.2"), "deepseek-v3.2")

    def test_append_bounded_caps_provider_output(self):
        from modules.freegpt import append_bounded

        text, reached_limit = append_bounded("1234", "56789", 7)

        self.assertEqual(text, "1234567")
        self.assertTrue(reached_limit)

    def test_generate_image_bounds_model_discovery_timeout(self):
        from modules.freegpt import _generate_image

        calls = {}

        class FakePollinations:
            @classmethod
            def get_models(cls, **kwargs):
                calls["get_models"] = kwargs

        class FakeImages:
            def generate(self, **kwargs):
                return "response"

        class FakeClient:
            def __init__(self, **kwargs):
                self.images = FakeImages()

        modules = {
            "g4f.client": types.SimpleNamespace(Client=FakeClient),
            "g4f.Provider.Pollinations": types.SimpleNamespace(
                Pollinations=FakePollinations
            ),
            "g4f.Provider.PollinationsImage": types.SimpleNamespace(
                PollinationsImage=object()
            ),
        }
        with patch.dict(sys.modules, modules):
            self.assertEqual(_generate_image("circle"), "response")

        self.assertEqual(calls["get_models"], {"timeout": 15})


class FreeGPTHandlerTest(unittest.IsolatedAsyncioTestCase):
    async def test_ai_handler_closes_stream_after_response_cap(self):
        from modules import freegpt

        class FakeStream:
            def __init__(self):
                self.closed = False

            def close(self):
                self.closed = True

        stream = FakeStream()
        msg = types.SimpleNamespace(
            text=".ai question",
            chat=types.SimpleNamespace(id=1),
            message_thread_id=None,
            edit=AsyncMock(),
        )
        client = types.SimpleNamespace(send_message=AsyncMock())

        with (
            patch.object(freegpt, "MAX_AI_RESPONSE_CHARS", 7),
            patch.object(freegpt, "_create_stream", return_value=stream),
            patch.object(freegpt, "_next_content", return_value=("12345678", False)),
            patch.object(freegpt, "_safe_edit", new=AsyncMock()),
        ):
            await freegpt.ai_handler(client, msg)

        self.assertTrue(stream.closed)


if __name__ == "__main__":
    unittest.main()
